/// The seam between "we generated a file" and "the bytes live somewhere".
/// Deliberately narrow: put, get, delete, and nothing about URLs.
///
/// One caller: the payroll exporter. This app deliberately holds no personnel
/// documents — no I-9, no W-4, no licence scans — so a generated timesheet is
/// the only file it ever stores.
///
/// No URL, because a timesheet still names everybody who works here and what
/// they were paid for. A storage backend that hands out a public link, however
/// long and random, makes those bytes reachable by anyone who ever sees the
/// link: a forwarded email, a browser history, a proxy log. Every download
/// therefore goes through an authorised route in this app, which means the
/// interface never needs to produce a URL and a backend is never asked for one.
///
/// Adding a provider (S3, Vercel Blob, Azure) means writing one class, the same
/// shape as the payroll exporter pattern in the brief.
export interface FileStorage {
  /// Stores the bytes and returns the key needed to read them back. The key is
  /// generated by the backend and is unguessable; nothing about the uploaded
  /// filename is used to build it.
  put(bytes: Buffer, meta: PutOptions): Promise<StoredFileRef>;

  /// Reads the bytes back. Throws if the key is unknown — a metadata row whose
  /// bytes have gone is a bug worth hearing about, not an empty download.
  get(storageKey: string): Promise<Buffer>;

  /// Removes the bytes. Succeeds if they are already gone, so a retried delete
  /// is not an error.
  delete(storageKey: string): Promise<void>;
}

export interface PutOptions {
  /// Used only for logging and content-type round-tripping. Never used to build
  /// a path or a key.
  filename: string;
  contentType: string;
}

export interface StoredFileRef {
  storageKey: string;
  sizeBytes: number;
  /// SHA-256 of the bytes, hex. Lets a download be checked against what was
  /// stored — "is this the file we sent to payroll?" has an answer.
  checksum: string;
}

/// Nest injection token. An interface cannot be injected directly.
export const FILE_STORAGE = 'FILE_STORAGE';
